---
- name: Call API with Bearer Token
  hosts: localhost
  gather_facts: false

  vars:
    api_url:  "{{ lookup('cypher','secret=secret/my_appliance') }}/api/instances?max=25&offset=0&showDeleted=false&details=false"
    bearer_token: "YOUR_BEARER_TOKEN"

  tasks:
    - name: Make GET request to API
      uri:
        url: "{{ api_url }}"
        method: GET
        headers:
          Authorization: "{{ lookup('cypher','secret=secret/morph_api_token_2025') }}"
        return_content: yes
        status_code: 200
      register: api_response

    - name: Show API response
      debug:
        msg: "{{ api_response.content }}"
