---
- name: Create VDI Pool
  hosts: localhost
  vars:
    vdi_data:
      name: "{{ morpheus.customOptions.poolName }}"
      description: "Created via Ansible"
      owner: 1
      minIdle: 0
      initialPoolSize: 1
      maxIdle: 0
      maxPoolSize: 2
      persistentUser: false
      recyclable: false
      allowCopy: false
      allowPrinter: false
      allowFileshare: false
      allowHypervisorConsole: false
      autoCreateLocalUserOnReservation": true
      enabled: true
      iconPath: "/assets/branding/140x40/resource.svg"
      config:
        myconfig:
        group:
          id: '3'
          name: VMWareGroup
        cloud:
          id: 1
          name: Denver vCenter
        type: windows
        name: "{{ morpheus.customOptions.VDI_Instance_name}}"
        instance:
          userGroup:
            id: ''
          configEnabled: false
        config:
          createUser: true
          isEC2: false
          isVpcSelectable: true
          noAgent: false
          smbiosAssetTag:
          nestedVirtualization:
          hostId:
          vmwareFolderId: "/"
          resourcePoolId: 3
          poolProviderType:
          executeMode: executeHost
        volumes:
        - id: 172
          name: root
          controllerId: 284
          controllerMountPoint: 284:0:5:0
          resizeable: true
          planResizable: true
          rootVolume: true
          unitNumber: '0'
          typeId: 1
          configurableIOPS: false
          maxStorage: 85899345920
          displayOrder: 0
          maxIOPS:
          uuid: a97131a8-2195-48b5-a44e-72baaef453d5
          virtualImageId: 160
          size: 80
          minStorage: 17179869184
          vId: 160
          volumeCustomizable: true
          readonlyName: false
          storageType: 1
          datastoreId: auto
        hostName: "{{ morpheus.customOptions.VDI_Instance_name}}"
        configEnabled: true
        layout:
          id: 243
          code: vmware-windows-2012_r2-single
        networkInterfaces:
        - primaryInterface: true
          network:
            id: network-4
            hasPool: false
            idName: VLAN0002 - Internal Server 2
          ipMode: ''
          showNetworkPoolLabel: false
          showNetworkDhcpLabel: true
        plan:
          id: 175
          code: vm-8192
        version: 2012 r2
        ports:
        - id: 24
          code: windows.3389
          name: RDP
          shortName: console
          internalPort: 3389
          externalPort: 3389
          loadBalancePort:
          sortOrder: 0
          loadBalanceProtocol:
          loadBalance: false
          visible: true
        metadata:
        - name: myTag
          value: "{{ morpheus.customOptions.myTagField }}"
        labels:
          - myLabel1
          - myLabel2
        executionId: d445c10f-afcb-4a6c-8baf-e1870f235e7c
        backup:
          createBackup: false
          jobAction: new
          jobRetentionCount:
          veeamManagedServer: ''
        loadBalancer: []
        hideLock: true
        hasNetworks: true
        displayNetworks:
        - name: VLAN0002 - Internal Server 2
          ipMode: Default
          usePool: false
          dhcpServer: true
        showScale: false
        hasPreview: false
        volumesDisplay:
        - storage: ''
          name: root
          controller: SCSI
          datastore: Auto - Datastore
          displayOrder: 0
          size: 80
          mountPoint: '0'
            
  
  tasks:
    - name: debug message
      ansible.builtin.debug:
        msg: "json data = {{ vdi_data }}"
        verbosity: 2 
        
    - name: Create VDI Pool
      uri:
        url: "{{ lookup('cypher','secret=secret/my_appliance') }}/api/vdi-pools"
        method: POST
        headers:
          Content-Type: application/json
          Authorization: "{{ lookup('cypher','secret=secret/my_token2') }}"
        body_format: json
        body:
          vdiPool: "{{ vdi_data }}"
        validate_certs: false
        return_content: true
        status_code: 200
