---
- name: Create VDI Pool
  hosts: localhost
  vars:
    vdi_data:
      name: "{{ morpheus.customOptions.poolName }}"
      description: "Created via Ansible"
      owner: 1
      minIdle: 0
      initialPoolSize: 1
      maxIdle: 0
      maxPoolSize: 2
      persistentUser: false
      recyclable: false
      allowCopy: false
      allowPrinter: false
      allowFileshare: false
      allowHypervisorConsole: false
      autoCreateLocalUserOnReservation": true
      enabled: true
      iconPath: "/assets/branding/140x40/resource.svg"
      config:
        zoneId: 1
        instance:
          name: wa-inst-02
          cloud: Denver vCenter
          site:
            id: 3
          type: windows
          instanceType:
            code: windows
          labels:
          - foo
          - bar
          layout:
            id: 243
            code: vmware-windows-2012_r2-single
          plan:
            id: 175
            code: vm-8192
            name: 2 CPU, 8GB Memory
        config:
          resourcePoolId: 3
          noAgent: 'off'
          nestedVirtualization: 'off'
          createUser: true
        volumes:
        - id: -1
          rootVolume: true
          name: root
          size: 80
          sizeId:
          storageType: 1
          datastoreId: auto
        networkInterfaces:
        - network:
            id: network-4
        layoutSize: 1
        hostName: wa-inst-02
        ports:
        - name: RDP
          port: 3389
          lb: ''
        tags:
        - name: tagname1
          value: tagval1
        - name: tagname2
          value: tagval2

            
  
  tasks:
    - name: debug message
      ansible.builtin.debug:
        msg: "json data = {{ vdi_data }}"
        verbosity: 2 
        
    - name: Create VDI Pool
      uri:
        url: "{{ lookup('cypher','secret=secret/my_appliance') }}/api/vdi-pools"
        method: POST
        headers:
          Content-Type: application/json
          Authorization: "{{ lookup('cypher','secret=secret/my_token2') }}"
        body_format: json
        body:
          vdiPool: "{{ vdi_data }}"
        validate_certs: false
        return_content: true
        status_code: 200
