---
- name: Create VDI Pool
- hosts: local
  vars:
    vdi_data: "{{ lookup('file','input.json') | from_json }}"
  
  tasks:
    - name: Create VDI Pool
      uri:
        url: "{{ lookup('cypher','secret=secret/my_appliance') }}/api/vdi-pools"
        method: POST
        headers:
          Content-Type: application/json
          Authorization: BEARER "{{ lookup('cypher','secret=secret/my_token') }}"
        body_format: json
        body:
          vdiPool: "{{ vdi_data }}"
        validate_certs: false
        return_content: true
        status_code: 200
