---
- name: Create VDI Pool
  hosts: localhost
  vars:
    vdi_data: "{{ lookup('file','input2.json') }}"
     
  
  tasks:
    - name: debug message
      ansible.builtin.debug:
        msg: "json data = {{ vdi_data }}"
        verbosity: 2 
        
    - name: Create VDI Pool
      uri:
        url: "{{ lookup('cypher','secret=secret/my_appliance') }}/api/vdi-pools"
        method: POST
        headers:
          Content-Type: application/json
          Authorization: "{{ lookup('cypher','secret=secret/my_token2') }}"
        body_format: json
        body:
          vdiPool: "{{ vdi_data }}"
        validate_certs: false
        return_content: true
        status_code: 200
