---
- hosts: all
  become: yes
  tasks:
    - name: Create a login user
      user:
        name: 'ansibleuser'
        password: '$6$ks11f672sdewQeaE$tAuVuvvKYq2K2Yq2mExLOOuHy0e7MyzxOBndwWPBzysyJHvfZghH4mk.KGcPlfZ7besMaEObPtV1GobG
WScm8.'
        groups: 
          - sudo
        state: absent
        shell: /bin/bash
        system: no
        createhome: yes
        home: /home/ansibleuser
