---
- name: Cypher Test
  hosts: all
 
  tasks:
    - name: Print out a Cypher secret 
      vars: 
        msg: |
          Morpheus Secret Test :
          --------------------------------
          {{ ansible_morpheus_url }}
          {{ ansible_morpheus_token}}
          {{ lookup('cypher','secret=secret/squirrel')}} 
          
      debug: 
        msg: "{{ msg.split('\n') }}"       
      tags: cypher_info