---
- name: Cypher Test
  hosts: localhost
 
  tasks:
    - name: Print out a Cypher secret 
      vars: 
        msg: |
          Morpheus Secret Test :
          --------------------------------
          {{ ansible_morpheus_url }}
          {{ lookup('cypher','secret=secret/testkey001',true)}} 
          
      # debug: 
      #   msg: "{{ msg.split('\n') }}"       
      # tags: cypher_info