# - name: Extract URL
#           ansible.builtin.set_fact:
#             api_url: "{{ morpheus.container.cloudConfig.agentInstall | regex_replace('.*\"(https://.*?apiKey=[a-f0-9-]+)\".*', '\\1') }}"
 
#         - name: Print the URL
#           ansible.builtin.debug:
#             var: api_url
 
#         - name: Download content from URL
#           ansible.builtin.get_url:
#             url: "{{ api_url }}"
#             dest: /tmp/software/morpheus_agent.sh
#             mode: "0755"
 
#         - name: Install Morpheus Agent
#           ansible.builtin.shell:
#             cmd: /tmp/software/morpheus_agent.sh
#           args:
#             creates: /usr/bin/morpheus-node-ctl

---
- name: dump all
  hosts: all
 
  tasks:
    - name: Print some debug information 
      vars: 
        msg: |
          Module Variables ("vars"):
          --------------------------------
         {{ morpheus.container.cloudConfig.agentInstall | regex_replace('.*\"(https://.*?apiKey=[a-f0-9-]+)\".*', '\\1') }}
        
      debug: 
        msg: "{{ msg.split('\n') }}"       
      tags: debug_info

