---
- name: Extract URL
  ansible.builtin.set_fact: null
  api_url: "{{ morpheus.container.cloudConfig.agentInstall |
    regex_replace('.*\"(https://.*?apiKey=[a-f0-9-]+)\".*', '\\1') }}"
- name: Print the URL
  ansible.builtin.debug: null
  var: api_url
 
        # - name: Download content from URL
        #   ansible.builtin.get_url:
        #     url: "{{ api_url }}"
        #     dest: /tmp/software/morpheus_agent.sh
        #     mode: "0755"
 
        # - name: Install Morpheus Agent
        #   ansible.builtin.shell:
        #     cmd: /tmp/software/morpheus_agent.sh
        #   args:
        #     creates: /usr/bin/morpheus-node-ctl


