---
- name: main playbook   
  hosts: all
  gather_facts: true

  gather_facts: no # is necessary because setup.py depends on Python too

  pre_tasks:
  - name: "Make sure remote system is initialized correctly"
    raw: 'ln -s /usr/bin/python3 /usr/bin/python'
    register: set_symlink
    failed_when: set_symlink.rc != 0 and set_symlink.rc != 1

    
  tasks:
    - name: Extract URL
      ansible.builtin.set_fact:
        api_url: "{{ morpheus.container.cloudConfig.agentInstall | regex_replace('.*\"(https://.*?apiKey=[a-f0-9-]+)\".*', '\\1') }}"
    - name: Print the URL
      ansible.builtin.debug:
        var: api_url
        
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /tmp/software
        state: directory
        mode: '0755'
 
    - name: Download content from URL
      ansible.builtin.get_url:
        url: "{{ api_url }}"
        validate_certs: false
        dest: /tmp/software/morpheus_agent.sh
        mode: "0755"
 
    - name: Install Morpheus Agent On Debian/Ubuntu
      ansible.builtin.shell:
        cmd: bash /tmp/software/morpheus_agent.sh
      args:
        creates: /usr/bin/morpheus-node-ctl
      when:
        - ansible_facts['distribution'] == "Ubuntu"


