---
- hosts: localhost
  tasks:
  - name: Pause for 5 minutes
    ansible.builtin.pause:
      seconds: 5
  - name: Waited for 5 min
    debug:
      msg:
      - "Hello World"
  
  - name: Write hostname to file
    ansible.builtin.copy:
      content: "Teardown host\n"
      dest: /tmp/teardown_task_ansible.txt
