---
- name: Playbook that runs for 2 minutes
  hosts: all
  gather_facts: no
  tasks:
    - name: Start message
      debug:
        msg: "Starting the 2-minute playbook."

    - name: Wait for 2 minutes
      pause:
        minutes: 2

    - name: End message
      debug:
        msg: "2 minutes have passed. Playbook finished."
