---
- hosts: localhost
  tasks:
  - name: Pause for 1 minutes
    ansible.builtin.pause:
      minutes: 1
  - name: Waited for 10 min
    debug:
      msg:
      - "Hello World"
  
  - name: Write to file
    lineinfile:
      path: /tmp/teardown_task_ansible.txt
      line: "Teardown host\n"
      create: yes
  
  # - name: Write hostname to file
  #   ansible.builtin.copy:
  #     content: "Teardown host\n"
  #     d: /tmp/teardown_task_ansible.txt
